version: '2.1'
services:

  mydb:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: test_qa
      MYSQL_PASSWORD: qa_test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"-uroot", "-proot", "ping", "-h", "127.0.0.1"]
      timeout: 30s
      retries: 10

  vk_api:
    image: "vk_api:latest"
    ports:
      - "5000:5000"

  myapp:
    image: "myapp:latest"
    volumes:
      - ../docker/config:/config
    ports:
      - "8082:8080"
    command: ["/app/myapp", "--config=/config/config.ini"]
    depends_on:
      mydb:
        condition: service_healthy
      vk_api:
        condition: service_started

#  selenoid:
#    image: "aerokube/selenoid:latest-release"
#    container_name: selenoid
#    networks:
#      - default
#    volumes:
#      - /etc/selenoid:/etc/selenoid
#      - /var/run/docker.sock:/var/run/docker.socks
#    ports:
#      - "4444:4444"
#    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "selenoid"]

networks:
  default:
    external:
      name: test_network
